#import <Foundation/Foundation.h>
#import <Capacitor/Capacitor.h>

// Generated by @aparajita/capacitor-native-decorator/make-ios-plugin

CAP_PLUGIN(LoggerBridge, "LoggerBridge",
  CAP_PLUGIN_METHOD(log, CAPPluginReturnNone);
  CAP_PLUGIN_METHOD(setUseSyslog, CAPPluginReturnNone);
)
